#!/usr/bin/env php
<?php
if (!isset($argv[1])) {
    trigger_error('Missing file name', E_USER_ERROR);
}
// Source file to parse
$sourceFile = $argv[1];
if (!file_exists($sourceFile)) {
    trigger_error('File "'.$sourceFile.'" does not exist', E_USER_ERROR);
}

// Get uncommited lines number
$exec = exec('git blame '.escapeshellarg($sourceFile).' | egrep -oh \'^00000000.*?([0-9]+)\)\' | egrep -oh \'([0-9]+)\)$\' | sed -e \'s/)//g\'', $uncommitedLines, $return);
if ($return !== 0) {
    trigger_error('Finding uncommited lines failed', E_USER_ERROR);
}
// Generate a fixed copy of source file
$fixedFile = tempnam(sys_get_temp_dir(), '');
copy($sourceFile, $fixedFile);
// Can't check php-cs-fixer return code because it return 1 if changes are made
exec('php-cs-fixer fix '.escapeshellarg($fixedFile), $output, $return);

// Compute diff between files
$diffCmd = 'diff -u '.escapeshellarg($sourceFile).' '.escapeshellarg($fixedFile);
$patch = shell_exec($diffCmd);
// Blame start line at 1, unlike diff
foreach ($uncommitedLines as $k => $v) {
    --$uncommitedLines[$k];
}
$countUncommitedLines = count($uncommitedLines);
// We got a diff
$exitCode = 0;
if (!empty($patch)) {
    $patches = preg_split('~^@@~m', $patch);
    $finalPatch = $patches[0];
    array_shift($patches);
    $countPatches = count($patches);
    $applyFinalPatch = false;
    // each chunk
    for ($j = 0; $j < $countPatches; ++$j) {
        $patch = $patches[$j];
        // If the chunk contains an uncommited line
        // add it to the final patch
        if (preg_match('~^\s*-([0-9]+),([0-9]+)~', $patch, $matches)) {
            $startPatch = $matches[1];
            $endPatch = $startPatch + $matches[2];
            for ($i = 0; $i < $countUncommitedLines; ++$i) {
                $line = $uncommitedLines[$i];
                if ($startPatch <= $line && $line <= $endPatch) {
                    $finalPatch .= '@@'.$patch;
                    $i = $countUncommitedLines;
                    $applyFinalPatch = true;
                }
            }
        }
    }
    // Apply final patch on the sourceFile if needed
    if ($applyFinalPatch) {
        echo "Formatting errors detected applying patch:\n$finalPatch\n";
        $patchFile = tempnam(sys_get_temp_dir(), '');
        file_put_contents($patchFile, $finalPatch);
        shell_exec('patch '.escapeshellarg($sourceFile).' < '.escapeshellarg($patchFile));
        unlink($patchFile);
        $exitCode = 1;
    }
}
if($exitCode !== 1) {
    echo "No formatting errors detected in ".$sourceFile."\n";
}
unlink($fixedFile);
exit($exitCode);
